[versions]
asciidoctorPlugin = "4.0.4"
assertj = "3.27.3"
commons-io = "2.18.0"
commons-lang3 = "3.17.0"
compile-testing = "0.21.0"
dependencyCheck = "12.1.0"
dummymaker = "4.0.0"
guava = "33.4.0-jre"
jakarta-annotation-api = "1.3.5"
javapoet = "1.13.0"
jsr250 = "1.0"
jupiter = "5.12.1"
mapstruct = "1.4.0.Final"
mockito = "5.16.0"
spring = "5.0.0.RELEASE"
springBoot = "2.7.18"
springDependencyManagement = "1.1.7"
versionsPlugin = "0.52.0"

[libraries]
assertj = { group = "org.assertj", name = "assertj-core", version.ref = "assertj"}
commons-io = { group = "commons-io", name = "commons-io", version.ref = "commons-io" }
commons-lang3 = { group = "org.apache.commons", name = "commons-lang3", version.ref = "commons-lang3" }
compile-testing = { group = "com.google.testing.compile", name = "compile-testing", version.ref = "compile-testing" }
dummymaker = { group = "com.github.goodforgod", name = "dummymaker", version.ref = "dummymaker"}
guava = { group = "com.google.guava", name = "guava", version.ref = "guava" }
jakarta-annotation = { group = "jakarta.annotation", name = "jakarta.annotation-api", version.ref = "jakarta-annotation-api" }
javapoet = { group = "com.squareup", name = "javapoet", version.ref = "javapoet"}
jsr250 = { group = "javax.annotation", name = "jsr250-api", version.ref = "jsr250" }
junit-jupiter-api = { group = "org.junit.jupiter", name = "junit-jupiter-api", version.ref = "jupiter" }
junit-jupiter-engine = { group = "org.junit.jupiter", name = "junit-jupiter-engine", version.ref = "jupiter" }
junit-jupiter-params = { group = "org.junit.jupiter", name = "junit-jupiter-params", version.ref = "jupiter" }
mapstruct-core = { group = "org.mapstruct", name = "mapstruct", version.ref = "mapstruct" }
mapstruct-processor = { group = "org.mapstruct", name = "mapstruct-processor", version.ref = "mapstruct" }
mockito = { group = "org.mockito", name = "mockito-junit-jupiter", version.ref = "mockito" }
spring-boot-starter-core = { group = "org.springframework.boot", name = "spring-boot-starter" }
spring-boot-starter-test = { group = "org.springframework.boot", name = "spring-boot-starter-test", version.ref = "springBoot" }
spring-context = { group = "org.springframework", name = "spring-context", version.ref = "spring" }
spring-core = { group = "org.springframework", name = "spring-core", version.ref = "spring" }
spring-test = { group = "org.springframework", name = "spring-test", version.ref = "spring" }

[bundles]
junit-jupiter = ["junit-jupiter-api", "junit-jupiter-engine", "junit-jupiter-params"]

[plugins]
asciidoctor = { id = "org.asciidoctor.jvm.convert", version.ref = "asciidoctorPlugin"}
dependencycheck = { id = "org.owasp.dependencycheck", version.ref = "dependencyCheck" }
spring-dependency-management = { id = "io.spring.dependency-management", version.ref = "springDependencyManagement" }
spring-boot = { id = "org.springframework.boot", version.ref = "springBoot" }
vers = { id = "com.github.ben-manes.versions", version.ref = "versionsPlugin" }
